using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CaddyUi.Domain.Routing;

namespace CaddyUi.Application.Routing;

public sealed record CaddyDnsProviderSource(
    string ProviderType,
    bool Enabled,
    bool ModuleInstalled,
    IReadOnlyDictionary<string, string> Settings,
    IReadOnlyDictionary<string, string> SecretReferences);

public sealed record CaddyRouteSource(
    ManagedRouteDefinition Route,
    string AccessGroupName,
    string DomainCertificateMode = "wildcard",
    CaddyDnsProviderSource? DnsProvider = null);

public sealed record CaddyCompilation(
    string Content,
    string Digest,
    string ManifestJson,
    IReadOnlyList<string> Warnings,
    bool RequiresWildcardCertificateRenderer,
    bool CertificateReadyForActiveApply);

public sealed class CaddyRouteCompiler
{
    private readonly bool _allowCustomRoutes;
    private readonly string _portalUpstream;

    public CaddyRouteCompiler(bool allowCustomRoutes, string portalUpstream)
    {
        _allowCustomRoutes = allowCustomRoutes;
        _portalUpstream = NormalizePortalUpstream(portalUpstream);
    }

    public CaddyCompilation Compile(IEnumerable<CaddyRouteSource> sources)
    {
        ArgumentNullException.ThrowIfNull(sources);
        var routes = sources
            .Where(source => source.Route.Enabled)
            .OrderBy(source => source.Route.Host, StringComparer.Ordinal)
            .ThenBy(source => source.Route.SortOrder)
            .ThenBy(source => source.Route.Name, StringComparer.Ordinal)
            .ThenBy(source => source.Route.Id)
            .ToArray();
        ValidateUniqueness(routes);

        var domains = BuildDomainSources(routes);
        ValidateCertificateConsistency(routes, domains);

        var warnings = new List<string>();
        var certificateManifest = new List<CertificateManifestItem>();
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Caddy UI 2.0. Do not edit this file manually.");
        builder.AppendLine("# Schema: managed-routes-v3");
        builder.AppendLine();

        var processedRoutes = new HashSet<Guid>();
        var usesWildcardCertificates = false;
        var requiresWildcardRenderer = false;
        var certificateReady = true;

        foreach (var domain in domains.Values
                     .OrderBy(item => item.DomainName, StringComparer.Ordinal)
                     .ThenBy(item => item.DomainId))
        {
            var domainRoutes = routes
                .Where(source => source.Route.DomainId == domain.DomainId)
                .ToArray();
            var wildcardRoutes = domainRoutes
                .Where(source => UsesWildcardCertificate(source, domains))
                .ToArray();
            var deepWildcardRoutes = wildcardRoutes
                .Where(source => !IsBaseHost(source.Route.Host, domain.DomainName) &&
                                 !IsDirectSubdomain(source.Route.Host, domain.DomainName))
                .ToArray();
            foreach (var source in deepWildcardRoutes)
            {
                warnings.Add(
                    $"{source.Route.Host} wird von *.{domain.DomainName} nicht abgedeckt. Verwende eine eigene verwaltete Domain oder ein Einzelzertifikat.");
            }

            var requestWildcard = domain.RequestWildcardCertificate ||
                                  wildcardRoutes.Any(source =>
                                      IsDirectSubdomain(source.Route.Host, domain.DomainName));
            var requestBase = domain.RequestBaseCertificate ||
                              wildcardRoutes.Any(source => IsBaseHost(source.Route.Host, domain.DomainName));
            var hasIndividualBaseRoute = domainRoutes.Any(source =>
                !UsesWildcardCertificate(source, domains) &&
                IsBaseHost(source.Route.Host, domain.DomainName));

            if (!requestWildcard && (!requestBase || hasIndividualBaseRoute) && wildcardRoutes.Length == 0)
            {
                continue;
            }

            var addresses = new List<string>();
            if (requestWildcard)
            {
                addresses.Add($"*.{domain.DomainName}");
                usesWildcardCertificates = true;
            }

            if (requestBase && !hasIndividualBaseRoute)
            {
                addresses.Add(domain.DomainName);
            }

            var dnsState = requestWildcard
                ? ResolveDnsChallengeState(domain.DomainName, domain.Provider, warnings)
                : CertificateState.Individual;
            var domainReady = dnsState.Ready && deepWildcardRoutes.Length == 0;
            certificateReady &= domainReady;
            requiresWildcardRenderer |= requestWildcard && !dnsState.Ready;

            foreach (var address in addresses)
            {
                certificateManifest.Add(new CertificateManifestItem(
                    address,
                    address.StartsWith("*.", StringComparison.Ordinal) ? "wildcard" : "base",
                    dnsState.ProviderType,
                    domainReady,
                    dnsState.Error));
            }

            if (addresses.Count == 0)
            {
                continue;
            }

            builder.Append(string.Join(", ", addresses)).AppendLine(" {");
            AppendCertificateConfiguration(builder, dnsState);
            foreach (var source in wildcardRoutes.Where(source =>
                         !deepWildcardRoutes.Any(deep => deep.Route.Id == source.Route.Id)))
            {
                if (IsBaseHost(source.Route.Host, domain.DomainName) && !requestBase ||
                    IsDirectSubdomain(source.Route.Host, domain.DomainName) && !requestWildcard)
                {
                    continue;
                }

                AppendRoute(builder, source, warnings, includeHostMatcher: true);
                processedRoutes.Add(source.Route.Id);
            }

            AppendFallback(builder);
            builder.AppendLine("}");
            builder.AppendLine();
        }

        foreach (var group in routes
                     .Where(source => !processedRoutes.Contains(source.Route.Id) &&
                                      !UsesWildcardCertificate(source, domains))
                     .GroupBy(source => source.Route.Host, StringComparer.Ordinal)
                     .OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            builder.Append(group.Key).AppendLine(" {");
            foreach (var source in group)
            {
                AppendRoute(builder, source, warnings, includeHostMatcher: false);
                processedRoutes.Add(source.Route.Id);
            }

            AppendFallback(builder);
            builder.AppendLine("}");
            builder.AppendLine();
            certificateManifest.Add(new CertificateManifestItem(
                group.Key,
                "individual",
                string.Empty,
                true,
                string.Empty));
        }

        var omitted = routes.Where(source => !processedRoutes.Contains(source.Route.Id)).ToArray();
        if (omitted.Length > 0)
        {
            certificateReady = false;
            foreach (var source in omitted)
            {
                warnings.Add($"Route {source.Route.Host}{source.Route.Configuration.PathPrefix} wurde wegen eines nicht erfüllten Zertifikatsplans nicht generiert.");
            }
        }

        requiresWildcardRenderer |= !certificateReady;

        if (routes.Length == 0 && builder.ToString().EndsWith("managed-routes-v3\n\n", StringComparison.Ordinal))
        {
            builder.AppendLine("# No enabled managed routes or requested domain certificates.");
        }

        var content = builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        var digest = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
        var manifest = new
        {
            schema = "managed-routes-v3",
            usesWildcardCertificates,
            requiresWildcardCertificateRenderer = requiresWildcardRenderer,
            certificateReadyForActiveApply = certificateReady,
            certificates = certificateManifest.Select(item => new
            {
                name = item.Name,
                mode = item.Mode,
                providerType = item.ProviderType,
                item.Ready,
                item.Error,
            }),
            domains = domains.Values
                .OrderBy(domain => domain.DomainName, StringComparer.Ordinal)
                .Select(domain => new
                {
                    id = domain.DomainId,
                    name = domain.DomainName,
                    wildcardRequested = domain.RequestWildcardCertificate,
                    baseDomainRequested = domain.RequestBaseCertificate,
                    providerType = domain.Provider?.ProviderType,
                }),
            routes = routes.Select(source => new
            {
                id = source.Route.Id,
                source.Route.Name,
                source.Route.Host,
                kind = ManagedRouteDefinition.ToStorageValue(source.Route.Kind),
                path = source.Route.Configuration.PathPrefix,
                source.Route.SortOrder,
                certificateMode = ManagedRouteDefinition.ToStorageValue(source.Route.CertificateMode),
                domainCertificateMode = EffectiveDomainCertificateMode(source, domains),
                accessGroupId = source.Route.AccessGroupId,
                accessGroupName = source.AccessGroupName,
                generated = processedRoutes.Contains(source.Route.Id),
            }),
        };
        return new CaddyCompilation(
            content,
            digest,
            JsonSerializer.Serialize(manifest),
            warnings,
            requiresWildcardRenderer,
            certificateReady);
    }

    private static Dictionary<Guid, CaddyDomainCertificateSource> BuildDomainSources(
        IReadOnlyCollection<CaddyRouteSource> routes)
    {
        var result = CaddyCertificateSourceRegistry.List()
            .ToDictionary(source => source.DomainId);
        foreach (var source in routes)
        {
            var routeUsesWildcard = source.Route.CertificateMode == RouteCertificateMode.Wildcard ||
                                    source.Route.CertificateMode == RouteCertificateMode.Inherit &&
                                    NormalizeDomainCertificateMode(source.DomainCertificateMode) == "wildcard";
            var needsWildcard = routeUsesWildcard &&
                                IsDirectSubdomain(source.Route.Host, source.Route.DomainName);
            var needsBase = routeUsesWildcard && IsBaseHost(source.Route.Host, source.Route.DomainName);
            if (result.TryGetValue(source.Route.DomainId, out var existing))
            {
                result[source.Route.DomainId] = existing with
                {
                    RequestWildcardCertificate = existing.RequestWildcardCertificate || needsWildcard,
                    RequestBaseCertificate = existing.RequestBaseCertificate || needsBase,
                    Provider = source.DnsProvider ?? existing.Provider,
                };
                continue;
            }

            result[source.Route.DomainId] = new CaddyDomainCertificateSource(
                source.Route.DomainId,
                source.Route.DomainName,
                source.DomainCertificateMode,
                needsWildcard,
                needsBase,
                source.DnsProvider);
        }

        return result;
    }

    private static void ValidateCertificateConsistency(
        IReadOnlyCollection<CaddyRouteSource> routes,
        IReadOnlyDictionary<Guid, CaddyDomainCertificateSource> domains)
    {
        foreach (var group in routes.GroupBy(source => source.Route.Host, StringComparer.Ordinal))
        {
            var modes = group
                .Select(source => UsesWildcardCertificate(source, domains))
                .Distinct()
                .ToArray();
            if (modes.Length > 1)
            {
                throw new InvalidOperationException(
                    $"Alle Routen für {group.Key} müssen denselben Zertifikatsmodus verwenden.");
            }
        }
    }

    private static CertificateState ResolveDnsChallengeState(
        string domainName,
        CaddyDnsProviderSource? provider,
        ICollection<string> warnings)
    {
        if (provider is null)
        {
            var error = $"Wildcard-Zertifikat für *.{domainName} ist noch keinem DNS-Provider zugeordnet.";
            warnings.Add(error);
            return CertificateState.Blocked(error);
        }

        if (!provider.Enabled)
        {
            var error = $"Der DNS-Provider für {domainName} ist deaktiviert.";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }

        if (!provider.ModuleInstalled)
        {
            var error = $"Das Caddy-DNS-Modul '{provider.ProviderType}' ist im laufenden Bundle nicht als installiert konfiguriert.";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }

        if (!string.Equals(provider.ProviderType, "netcup", StringComparison.OrdinalIgnoreCase))
        {
            var error = $"Für '{provider.ProviderType}' ist noch kein geprüfter Caddyfile-DNS-01-Renderer aktiviert. Provider-API und DDNS können separat verfügbar sein.";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }

        try
        {
            var customerNumber = Required(provider.Settings, "customer_number");
            var apiKey = EnvironmentPlaceholder(Required(provider.SecretReferences, "api_key"));
            var apiPassword = EnvironmentPlaceholder(Required(provider.SecretReferences, "api_password"));
            var endpoint = Optional(provider.Settings, "endpoint");
            return new CertificateState(
                true,
                true,
                "netcup",
                customerNumber,
                apiKey,
                apiPassword,
                endpoint,
                string.Empty);
        }
        catch (InvalidOperationException exception)
        {
            var error = $"Wildcard-Zertifikat für *.{domainName} ist nicht einsatzbereit: {exception.Message}";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }
    }

    private static string EffectiveDomainCertificateMode(
        CaddyRouteSource source,
        IReadOnlyDictionary<Guid, CaddyDomainCertificateSource> domains)
    {
        return NormalizeDomainCertificateMode(
            domains.TryGetValue(source.Route.DomainId, out var registered)
                ? registered.DomainCertificateMode
                : source.DomainCertificateMode);
    }

    private static void AppendCertificateConfiguration(StringBuilder builder, CertificateState state)
    {
        if (!state.RequiresDnsChallenge || !state.Ready)
        {
            return;
        }

        builder.AppendLine("    tls {");
        builder.AppendLine("        dns netcup {");
        builder.Append("            customer_number ").Append(CaddyQuote(state.CustomerNumber)).AppendLine();
        builder.Append("            api_key ").Append(CaddyQuote(state.ApiKey)).AppendLine();
        builder.Append("            api_password ").Append(CaddyQuote(state.ApiPassword)).AppendLine();
        if (state.Endpoint.Length > 0)
        {
            builder.Append("            endpoint ").Append(CaddyQuote(state.Endpoint)).AppendLine();
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private void AppendRoute(
        StringBuilder builder,
        CaddyRouteSource source,
        ICollection<string> warnings,
        bool includeHostMatcher)
    {
        var route = source.Route;
        var matcher = $"@route_{route.Id:N}";
        if (includeHostMatcher)
        {
            builder.Append("    ").Append(matcher).AppendLine(" {");
            builder.Append("        host ").Append(CaddyQuote(route.Host)).AppendLine();
            if (route.Configuration.PathPrefix != "/")
            {
                builder.Append("        path ")
                    .Append(CaddyQuote(route.Configuration.PathPrefix + "*"))
                    .AppendLine();
            }

            builder.AppendLine("    }");
            builder.Append("    handle ").Append(matcher).AppendLine(" {");
        }
        else if (route.Configuration.PathPrefix != "/")
        {
            builder.Append("    ").Append(matcher).Append(" path ")
                .Append(CaddyQuote(route.Configuration.PathPrefix + "*"))
                .AppendLine();
            builder.Append("    handle ").Append(matcher).AppendLine(" {");
        }
        else
        {
            builder.AppendLine("    handle {");
        }

        builder.Append("        # ").Append(route.Name).Append(" · ")
            .Append(ManagedRouteDefinition.ToStorageValue(route.Kind)).AppendLine();
        if (route.AccessGroupId is Guid accessGroupId)
        {
            builder.Append("        forward_auth ").Append(_portalUpstream).AppendLine(" {");
            builder.Append("            uri /__caddy_ui_auth/authorize?group=")
                .Append(accessGroupId.ToString("D")).AppendLine();
            builder.AppendLine("            copy_headers Remote-User X-Caddy-Portal-User");
            builder.AppendLine("        }");
        }

        switch (route.Kind)
        {
            case ManagedRouteKind.Proxy:
                AppendProxy(builder, route.Configuration);
                break;
            case ManagedRouteKind.Redirect:
                builder.Append("        redir ")
                    .Append(CaddyQuote(route.Configuration.RedirectTarget))
                    .Append(' ')
                    .Append(route.Configuration.RedirectPermanent ? "308" : "302")
                    .AppendLine();
                break;
            case ManagedRouteKind.StaticResponse:
                builder.Append("        respond ")
                    .Append(CaddyQuote(route.Configuration.StaticBody))
                    .Append(' ')
                    .Append(route.Configuration.StaticStatusCode)
                    .AppendLine();
                break;
            case ManagedRouteKind.Custom:
                if (!_allowCustomRoutes)
                {
                    throw new InvalidOperationException(
                        $"Custom route '{route.Name}' cannot be compiled because custom routes are disabled.");
                }

                warnings.Add($"Custom route '{route.Name}' contains administrator-supplied Caddyfile directives.");
                foreach (var line in route.Configuration.CustomSnippet.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
                {
                    builder.Append("        ").AppendLine(line);
                }

                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(route.Kind));
        }

        builder.AppendLine("    }");
    }

    private static void AppendProxy(StringBuilder builder, RouteConfigurationDocument configuration)
    {
        builder.Append("        reverse_proxy ").Append(CaddyQuote(configuration.Upstream));
        if (!configuration.PreserveHost && configuration.HealthPath.Length == 0)
        {
            builder.AppendLine();
            return;
        }

        builder.AppendLine(" {");
        if (configuration.PreserveHost)
        {
            builder.AppendLine("            header_up Host {host}");
        }

        if (configuration.HealthPath.Length > 0)
        {
            builder.Append("            health_uri ").Append(CaddyQuote(configuration.HealthPath)).AppendLine();
            builder.Append("            health_interval ")
                .Append(configuration.HealthIntervalSeconds)
                .AppendLine("s");
        }

        builder.AppendLine("        }");
    }

    private static void AppendFallback(StringBuilder builder)
    {
        builder.AppendLine("    handle {");
        builder.AppendLine("        respond \"No managed route matched\" 404");
        builder.AppendLine("    }");
    }

    private static bool UsesWildcardCertificate(
        CaddyRouteSource source,
        IReadOnlyDictionary<Guid, CaddyDomainCertificateSource> domains)
    {
        if (source.Route.CertificateMode == RouteCertificateMode.Wildcard)
        {
            return true;
        }

        if (source.Route.CertificateMode == RouteCertificateMode.Individual)
        {
            return false;
        }

        return EffectiveDomainCertificateMode(source, domains) == "wildcard";
    }

    private static bool IsBaseHost(string host, string domainName)
    {
        return string.Equals(host, domainName, StringComparison.Ordinal);
    }

    private static bool IsDirectSubdomain(string host, string domainName)
    {
        var suffix = $".{domainName}";
        if (!host.EndsWith(suffix, StringComparison.Ordinal))
        {
            return false;
        }

        var prefix = host[..^suffix.Length];
        return prefix.Length > 0 && !prefix.Contains('.', StringComparison.Ordinal);
    }

    private static string NormalizeDomainCertificateMode(string? value)
    {
        return string.Equals(value?.Trim(), "individual", StringComparison.OrdinalIgnoreCase)
            ? "individual"
            : "wildcard";
    }

    private static string EnvironmentPlaceholder(string reference)
    {
        var normalized = reference.Trim();
        if (normalized.StartsWith("secret://env/", StringComparison.OrdinalIgnoreCase))
        {
            normalized = normalized[13..];
        }
        else if (normalized.StartsWith("secret://", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException("Caddy DNS-01 kann nur Umgebungsvariablen referenzieren; Datei-Secrets bleiben für direkte API-Aufrufe nutzbar.");
        }

        if (normalized.Length == 0 || !(char.IsLetter(normalized[0]) || normalized[0] == '_') ||
            normalized.Any(character => !(char.IsLetterOrDigit(character) || character == '_')))
        {
            throw new InvalidOperationException("Die Secret-Referenz ist keine gültige Umgebungsvariable.");
        }

        return $"{{env.{normalized}}}";
    }

    private static string Required(IReadOnlyDictionary<string, string> values, string key)
    {
        return values.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value)
            ? value.Trim()
            : throw new InvalidOperationException($"Pflichtfeld '{key}' fehlt.");
    }

    private static string Optional(IReadOnlyDictionary<string, string> values, string key)
    {
        return values.TryGetValue(key, out var value) ? value.Trim() : string.Empty;
    }

    private static void ValidateUniqueness(IReadOnlyCollection<CaddyRouteSource> routes)
    {
        var duplicate = routes
            .GroupBy(
                source => (source.Route.Host, source.Route.Configuration.PathPrefix),
                StringTupleComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null)
        {
            throw new InvalidOperationException(
                $"Multiple enabled routes target {duplicate.Key.Host}{duplicate.Key.PathPrefix}.");
        }
    }

    private static string CaddyQuote(string value)
    {
        return $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal)}\"";
    }

    private static string NormalizePortalUpstream(string value)
    {
        var candidate = value.Trim();
        if (candidate.Length == 0 || candidate.Contains('\r') || candidate.Contains('\n') || candidate.Contains('{') || candidate.Contains('}'))
        {
            throw new ArgumentException("The portal upstream is invalid.", nameof(value));
        }

        return candidate;
    }

    private sealed record CertificateManifestItem(
        string Name,
        string Mode,
        string ProviderType,
        bool Ready,
        string Error);

    private sealed record CertificateState(
        bool RequiresDnsChallenge,
        bool Ready,
        string ProviderType,
        string CustomerNumber,
        string ApiKey,
        string ApiPassword,
        string Endpoint,
        string Error)
    {
        public static CertificateState Individual { get; } =
            new(false, true, string.Empty, string.Empty, string.Empty, string.Empty, string.Empty, string.Empty);

        public static CertificateState Blocked(string error, string providerType = "") =>
            new(true, false, providerType, string.Empty, string.Empty, string.Empty, string.Empty, error);
    }

    private sealed class StringTupleComparer : IEqualityComparer<(string Host, string PathPrefix)>
    {
        public static StringTupleComparer Ordinal { get; } = new();

        public bool Equals((string Host, string PathPrefix) x, (string Host, string PathPrefix) y)
        {
            return string.Equals(x.Host, y.Host, StringComparison.Ordinal) &&
                   string.Equals(x.PathPrefix, y.PathPrefix, StringComparison.Ordinal);
        }

        public int GetHashCode((string Host, string PathPrefix) obj)
        {
            return HashCode.Combine(
                StringComparer.Ordinal.GetHashCode(obj.Host),
                StringComparer.Ordinal.GetHashCode(obj.PathPrefix));
        }
    }
}
