using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CaddyUi.Domain.Routing;

namespace CaddyUi.Application.Routing;

public sealed record CaddyRouteSource(ManagedRouteDefinition Route, string AccessGroupName);

public sealed record CaddyCompilation(
    string Content,
    string Digest,
    string ManifestJson,
    IReadOnlyList<string> Warnings,
    bool RequiresWildcardCertificateRenderer);

public sealed class CaddyRouteCompiler
{
    private readonly bool _allowCustomRoutes;
    private readonly string _portalUpstream;

    public CaddyRouteCompiler(bool allowCustomRoutes, string portalUpstream)
    {
        _allowCustomRoutes = allowCustomRoutes;
        _portalUpstream = NormalizePortalUpstream(portalUpstream);
    }

    public CaddyCompilation Compile(IEnumerable<CaddyRouteSource> sources)
    {
        ArgumentNullException.ThrowIfNull(sources);
        var routes = sources
            .Where(source => source.Route.Enabled)
            .OrderBy(source => source.Route.Host, StringComparer.Ordinal)
            .ThenBy(source => source.Route.SortOrder)
            .ThenBy(source => source.Route.Name, StringComparer.Ordinal)
            .ThenBy(source => source.Route.Id)
            .ToArray();
        ValidateUniqueness(routes);

        var warnings = new List<string>();
        var requiresWildcardRenderer = routes.Any(source =>
            source.Route.CertificateMode != RouteCertificateMode.Individual);
        if (requiresWildcardRenderer)
        {
            warnings.Add(
                "Mindestens eine Route verwendet Wildcard oder erbt den Domainstandard. Der produktive Apply bleibt bis zum DNS-/Wildcard-Renderer aus Phase 8 gesperrt; Shadow-Validierung ist möglich.");
        }

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Caddy UI 2.0. Do not edit this file manually.");
        builder.AppendLine("# Schema: managed-routes-v1");
        builder.AppendLine();

        foreach (var group in routes.GroupBy(source => source.Route.Host, StringComparer.Ordinal))
        {
            builder.Append(group.Key).AppendLine(" {");
            foreach (var source in group)
            {
                AppendRoute(builder, source, warnings);
            }

            builder.AppendLine("    handle {");
            builder.AppendLine("        respond \"No managed route matched\" 404");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        if (routes.Length == 0)
        {
            builder.AppendLine("# No enabled managed routes.");
        }

        var content = builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        var digest = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
        var manifest = new
        {
            schema = "managed-routes-v1",
            requiresWildcardCertificateRenderer = requiresWildcardRenderer,
            routes = routes.Select(source => new
            {
                id = source.Route.Id,
                source.Route.Name,
                source.Route.Host,
                kind = ManagedRouteDefinition.ToStorageValue(source.Route.Kind),
                path = source.Route.Configuration.PathPrefix,
                source.Route.SortOrder,
                certificateMode = ManagedRouteDefinition.ToStorageValue(source.Route.CertificateMode),
                accessGroupId = source.Route.AccessGroupId,
                accessGroupName = source.AccessGroupName,
            }),
        };
        return new CaddyCompilation(
            content,
            digest,
            JsonSerializer.Serialize(manifest),
            warnings,
            requiresWildcardRenderer);
    }

    private void AppendRoute(
        StringBuilder builder,
        CaddyRouteSource source,
        ICollection<string> warnings)
    {
        var route = source.Route;
        var matcher = $"@route_{route.Id:N}";
        if (route.Configuration.PathPrefix != "/")
        {
            builder.Append("    ").Append(matcher).Append(" path ")
                .Append(CaddyQuote(route.Configuration.PathPrefix + "*"))
                .AppendLine();
            builder.Append("    handle ").Append(matcher).AppendLine(" {");
        }
        else
        {
            builder.AppendLine("    handle {");
        }

        builder.Append("        # ").Append(route.Name).Append(" · ")
            .Append(ManagedRouteDefinition.ToStorageValue(route.Kind)).AppendLine();
        if (route.AccessGroupId is Guid accessGroupId)
        {
            builder.Append("        forward_auth ").Append(_portalUpstream).AppendLine(" {");
            builder.Append("            uri /__caddy_ui_auth/authorize?group=")
                .Append(accessGroupId.ToString("D")).AppendLine();
            builder.AppendLine("            copy_headers Remote-User X-Caddy-Portal-User");
            builder.AppendLine("        }");
        }

        switch (route.Kind)
        {
            case ManagedRouteKind.Proxy:
                AppendProxy(builder, route.Configuration);
                break;
            case ManagedRouteKind.Redirect:
                builder.Append("        redir ")
                    .Append(CaddyQuote(route.Configuration.RedirectTarget))
                    .Append(' ')
                    .Append(route.Configuration.RedirectPermanent ? "308" : "302")
                    .AppendLine();
                break;
            case ManagedRouteKind.StaticResponse:
                builder.Append("        respond ")
                    .Append(CaddyQuote(route.Configuration.StaticBody))
                    .Append(' ')
                    .Append(route.Configuration.StaticStatusCode)
                    .AppendLine();
                break;
            case ManagedRouteKind.Custom:
                if (!_allowCustomRoutes)
                {
                    throw new InvalidOperationException(
                        $"Custom route '{route.Name}' cannot be compiled because custom routes are disabled.");
                }

                warnings.Add($"Custom route '{route.Name}' contains administrator-supplied Caddyfile directives.");
                foreach (var line in route.Configuration.CustomSnippet.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
                {
                    builder.Append("        ").AppendLine(line);
                }

                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(route.Kind));
        }

        builder.AppendLine("    }");
    }

    private static void AppendProxy(StringBuilder builder, RouteConfigurationDocument configuration)
    {
        builder.Append("        reverse_proxy ").Append(CaddyQuote(configuration.Upstream));
        if (!configuration.PreserveHost && configuration.HealthPath.Length == 0)
        {
            builder.AppendLine();
            return;
        }

        builder.AppendLine(" {");
        if (configuration.PreserveHost)
        {
            builder.AppendLine("            header_up Host {host}");
        }

        if (configuration.HealthPath.Length > 0)
        {
            builder.Append("            health_uri ").Append(CaddyQuote(configuration.HealthPath)).AppendLine();
            builder.Append("            health_interval ")
                .Append(configuration.HealthIntervalSeconds)
                .AppendLine("s");
        }

        builder.AppendLine("        }");
    }

    private static void ValidateUniqueness(IReadOnlyCollection<CaddyRouteSource> routes)
    {
        var duplicate = routes
            .GroupBy(
                source => (source.Route.Host, source.Route.Configuration.PathPrefix),
                StringTupleComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null)
        {
            throw new InvalidOperationException(
                $"Multiple enabled routes target {duplicate.Key.Host}{duplicate.Key.PathPrefix}.");
        }
    }

    private static string CaddyQuote(string value)
    {
        return $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal)}\"";
    }

    private static string NormalizePortalUpstream(string value)
    {
        var candidate = value.Trim();
        if (candidate.Length == 0 || candidate.Contains('\r') || candidate.Contains('\n') || candidate.Contains('{') || candidate.Contains('}'))
        {
            throw new ArgumentException("The portal upstream is invalid.", nameof(value));
        }

        return candidate;
    }

    private sealed class StringTupleComparer : IEqualityComparer<(string Host, string PathPrefix)>
    {
        public static StringTupleComparer Ordinal { get; } = new();

        public bool Equals((string Host, string PathPrefix) x, (string Host, string PathPrefix) y)
        {
            return string.Equals(x.Host, y.Host, StringComparison.Ordinal) &&
                   string.Equals(x.PathPrefix, y.PathPrefix, StringComparison.Ordinal);
        }

        public int GetHashCode((string Host, string PathPrefix) obj)
        {
            return HashCode.Combine(
                StringComparer.Ordinal.GetHashCode(obj.Host),
                StringComparer.Ordinal.GetHashCode(obj.PathPrefix));
        }
    }
}
