using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CaddyUi.Domain.Routing;

namespace CaddyUi.Application.Routing;

public sealed record CaddyDnsProviderSource(
    string ProviderType,
    bool Enabled,
    bool ModuleInstalled,
    IReadOnlyDictionary<string, string> Settings,
    IReadOnlyDictionary<string, string> SecretReferences);

public sealed record CaddyRouteSource(
    ManagedRouteDefinition Route,
    string AccessGroupName,
    string DomainCertificateMode = "wildcard",
    CaddyDnsProviderSource? DnsProvider = null);

public sealed record CaddyCompilation(
    string Content,
    string Digest,
    string ManifestJson,
    IReadOnlyList<string> Warnings,
    bool RequiresWildcardCertificateRenderer,
    bool CertificateReadyForActiveApply);

public sealed class CaddyRouteCompiler
{
    private readonly bool _allowCustomRoutes;
    private readonly string _portalUpstream;

    public CaddyRouteCompiler(bool allowCustomRoutes, string portalUpstream)
    {
        _allowCustomRoutes = allowCustomRoutes;
        _portalUpstream = NormalizePortalUpstream(portalUpstream);
    }

    public CaddyCompilation Compile(IEnumerable<CaddyRouteSource> sources)
    {
        ArgumentNullException.ThrowIfNull(sources);
        var routes = sources
            .Where(source => source.Route.Enabled)
            .OrderBy(source => source.Route.Host, StringComparer.Ordinal)
            .ThenBy(source => source.Route.SortOrder)
            .ThenBy(source => source.Route.Name, StringComparer.Ordinal)
            .ThenBy(source => source.Route.Id)
            .ToArray();
        ValidateUniqueness(routes);

        var warnings = new List<string>();
        var certificateStates = routes
            .GroupBy(source => source.Route.Host, StringComparer.Ordinal)
            .ToDictionary(
                group => group.Key,
                group => ResolveCertificateState(group.ToArray(), warnings),
                StringComparer.Ordinal);
        var usesWildcardCertificates = certificateStates.Values.Any(state => state.RequiresDnsChallenge);
        var certificateReady = certificateStates.Values.All(state => state.Ready);
        var requiresWildcardRenderer = certificateStates.Values.Any(state => state.RequiresDnsChallenge && !state.Ready);

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Caddy UI 2.0. Do not edit this file manually.");
        builder.AppendLine("# Schema: managed-routes-v2");
        builder.AppendLine();

        foreach (var group in routes.GroupBy(source => source.Route.Host, StringComparer.Ordinal))
        {
            builder.Append(group.Key).AppendLine(" {");
            AppendCertificateConfiguration(builder, certificateStates[group.Key]);
            foreach (var source in group)
            {
                AppendRoute(builder, source, warnings);
            }

            builder.AppendLine("    handle {");
            builder.AppendLine("        respond \"No managed route matched\" 404");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        if (routes.Length == 0)
        {
            builder.AppendLine("# No enabled managed routes.");
        }

        var content = builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        var digest = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
        var manifest = new
        {
            schema = "managed-routes-v2",
            usesWildcardCertificates,
            requiresWildcardCertificateRenderer = requiresWildcardRenderer,
            certificateReadyForActiveApply = certificateReady,
            certificates = certificateStates.Select(pair => new
            {
                host = pair.Key,
                mode = pair.Value.RequiresDnsChallenge ? "wildcard" : "individual",
                providerType = pair.Value.ProviderType,
                pair.Value.Ready,
                pair.Value.Error,
            }),
            routes = routes.Select(source => new
            {
                id = source.Route.Id,
                source.Route.Name,
                source.Route.Host,
                kind = ManagedRouteDefinition.ToStorageValue(source.Route.Kind),
                path = source.Route.Configuration.PathPrefix,
                source.Route.SortOrder,
                certificateMode = ManagedRouteDefinition.ToStorageValue(source.Route.CertificateMode),
                domainCertificateMode = EffectiveDomainCertificateMode(source),
                accessGroupId = source.Route.AccessGroupId,
                accessGroupName = source.AccessGroupName,
            }),
        };
        return new CaddyCompilation(
            content,
            digest,
            JsonSerializer.Serialize(manifest),
            warnings,
            requiresWildcardRenderer,
            certificateReady);
    }

    private static CertificateState ResolveCertificateState(
        IReadOnlyList<CaddyRouteSource> routes,
        ICollection<string> warnings)
    {
        var wildcardRoutes = routes.Where(UsesWildcardCertificate).ToArray();
        if (wildcardRoutes.Length == 0)
        {
            return CertificateState.Individual;
        }

        var host = routes[0].Route.Host;
        var providers = wildcardRoutes
            .Select(EffectiveProvider)
            .Where(provider => provider is not null)
            .Cast<CaddyDnsProviderSource>()
            .ToArray();
        if (providers.Length == 0)
        {
            var error = $"Wildcard-Zertifikat für {host} ist noch keinem DNS-Provider zugeordnet.";
            warnings.Add(error);
            return CertificateState.Blocked(error);
        }

        var provider = providers[0];
        if (providers.Any(item => !string.Equals(item.ProviderType, provider.ProviderType, StringComparison.OrdinalIgnoreCase)))
        {
            var error = $"Die Routen für {host} verweisen auf unterschiedliche DNS-Provider.";
            warnings.Add(error);
            return CertificateState.Blocked(error);
        }

        if (!provider.Enabled)
        {
            var error = $"Der DNS-Provider für {host} ist deaktiviert.";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }

        if (!provider.ModuleInstalled)
        {
            var error = $"Das Caddy-DNS-Modul '{provider.ProviderType}' ist im laufenden Bundle nicht als installiert konfiguriert.";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }

        if (!string.Equals(provider.ProviderType, "netcup", StringComparison.OrdinalIgnoreCase))
        {
            var error = $"Für '{provider.ProviderType}' ist noch kein geprüfter Caddyfile-DNS-01-Renderer aktiviert. Provider-API und DDNS können separat verfügbar sein.";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }

        try
        {
            var customerNumber = Required(provider.Settings, "customer_number");
            var apiKey = EnvironmentPlaceholder(Required(provider.SecretReferences, "api_key"));
            var apiPassword = EnvironmentPlaceholder(Required(provider.SecretReferences, "api_password"));
            var endpoint = Optional(provider.Settings, "endpoint");
            return new CertificateState(
                true,
                true,
                "netcup",
                customerNumber,
                apiKey,
                apiPassword,
                endpoint,
                string.Empty);
        }
        catch (InvalidOperationException exception)
        {
            var error = $"Wildcard-Zertifikat für {host} ist nicht einsatzbereit: {exception.Message}";
            warnings.Add(error);
            return CertificateState.Blocked(error, provider.ProviderType);
        }
    }

    private static CaddyDnsProviderSource? EffectiveProvider(CaddyRouteSource source)
    {
        return source.DnsProvider ?? CaddyCertificateSourceRegistry.Find(source.Route.DomainId)?.Provider;
    }

    private static string EffectiveDomainCertificateMode(CaddyRouteSource source)
    {
        var registered = CaddyCertificateSourceRegistry.Find(source.Route.DomainId);
        return NormalizeDomainCertificateMode(registered?.DomainCertificateMode ?? source.DomainCertificateMode);
    }

    private static void AppendCertificateConfiguration(StringBuilder builder, CertificateState state)
    {
        if (!state.RequiresDnsChallenge || !state.Ready)
        {
            return;
        }

        builder.AppendLine("    tls {");
        builder.AppendLine("        dns netcup {");
        builder.Append("            customer_number ").Append(CaddyQuote(state.CustomerNumber)).AppendLine();
        builder.Append("            api_key ").Append(CaddyQuote(state.ApiKey)).AppendLine();
        builder.Append("            api_password ").Append(CaddyQuote(state.ApiPassword)).AppendLine();
        if (state.Endpoint.Length > 0)
        {
            builder.Append("            endpoint ").Append(CaddyQuote(state.Endpoint)).AppendLine();
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private void AppendRoute(
        StringBuilder builder,
        CaddyRouteSource source,
        ICollection<string> warnings)
    {
        var route = source.Route;
        var matcher = $"@route_{route.Id:N}";
        if (route.Configuration.PathPrefix != "/")
        {
            builder.Append("    ").Append(matcher).Append(" path ")
                .Append(CaddyQuote(route.Configuration.PathPrefix + "*"))
                .AppendLine();
            builder.Append("    handle ").Append(matcher).AppendLine(" {");
        }
        else
        {
            builder.AppendLine("    handle {");
        }

        builder.Append("        # ").Append(route.Name).Append(" · ")
            .Append(ManagedRouteDefinition.ToStorageValue(route.Kind)).AppendLine();
        if (route.AccessGroupId is Guid accessGroupId)
        {
            builder.Append("        forward_auth ").Append(_portalUpstream).AppendLine(" {");
            builder.Append("            uri /__caddy_ui_auth/authorize?group=")
                .Append(accessGroupId.ToString("D")).AppendLine();
            builder.AppendLine("            copy_headers Remote-User X-Caddy-Portal-User");
            builder.AppendLine("        }");
        }

        switch (route.Kind)
        {
            case ManagedRouteKind.Proxy:
                AppendProxy(builder, route.Configuration);
                break;
            case ManagedRouteKind.Redirect:
                builder.Append("        redir ")
                    .Append(CaddyQuote(route.Configuration.RedirectTarget))
                    .Append(' ')
                    .Append(route.Configuration.RedirectPermanent ? "308" : "302")
                    .AppendLine();
                break;
            case ManagedRouteKind.StaticResponse:
                builder.Append("        respond ")
                    .Append(CaddyQuote(route.Configuration.StaticBody))
                    .Append(' ')
                    .Append(route.Configuration.StaticStatusCode)
                    .AppendLine();
                break;
            case ManagedRouteKind.Custom:
                if (!_allowCustomRoutes)
                {
                    throw new InvalidOperationException(
                        $"Custom route '{route.Name}' cannot be compiled because custom routes are disabled.");
                }

                warnings.Add($"Custom route '{route.Name}' contains administrator-supplied Caddyfile directives.");
                foreach (var line in route.Configuration.CustomSnippet.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
                {
                    builder.Append("        ").AppendLine(line);
                }

                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(route.Kind));
        }

        builder.AppendLine("    }");
    }

    private static void AppendProxy(StringBuilder builder, RouteConfigurationDocument configuration)
    {
        builder.Append("        reverse_proxy ").Append(CaddyQuote(configuration.Upstream));
        if (!configuration.PreserveHost && configuration.HealthPath.Length == 0)
        {
            builder.AppendLine();
            return;
        }

        builder.AppendLine(" {");
        if (configuration.PreserveHost)
        {
            builder.AppendLine("            header_up Host {host}");
        }

        if (configuration.HealthPath.Length > 0)
        {
            builder.Append("            health_uri ").Append(CaddyQuote(configuration.HealthPath)).AppendLine();
            builder.Append("            health_interval ")
                .Append(configuration.HealthIntervalSeconds)
                .AppendLine("s");
        }

        builder.AppendLine("        }");
    }

    private static bool UsesWildcardCertificate(CaddyRouteSource source)
    {
        return source.Route.CertificateMode == RouteCertificateMode.Wildcard ||
               source.Route.CertificateMode == RouteCertificateMode.Inherit &&
               EffectiveDomainCertificateMode(source) == "wildcard";
    }

    private static string NormalizeDomainCertificateMode(string? value)
    {
        return string.Equals(value?.Trim(), "individual", StringComparison.OrdinalIgnoreCase)
            ? "individual"
            : "wildcard";
    }

    private static string EnvironmentPlaceholder(string reference)
    {
        var normalized = reference.Trim();
        if (normalized.StartsWith("secret://env/", StringComparison.OrdinalIgnoreCase))
        {
            normalized = normalized[13..];
        }
        else if (normalized.StartsWith("secret://", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException("Caddy DNS-01 kann nur Umgebungsvariablen referenzieren; Datei-Secrets bleiben für direkte API-Aufrufe nutzbar.");
        }

        if (normalized.Length == 0 || !(char.IsLetter(normalized[0]) || normalized[0] == '_') ||
            normalized.Any(character => !(char.IsLetterOrDigit(character) || character == '_')))
        {
            throw new InvalidOperationException("Die Secret-Referenz ist keine gültige Umgebungsvariable.");
        }

        return $"{{env.{normalized}}}";
    }

    private static string Required(IReadOnlyDictionary<string, string> values, string key)
    {
        return values.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value)
            ? value.Trim()
            : throw new InvalidOperationException($"Pflichtfeld '{key}' fehlt.");
    }

    private static string Optional(IReadOnlyDictionary<string, string> values, string key)
    {
        return values.TryGetValue(key, out var value) ? value.Trim() : string.Empty;
    }

    private static void ValidateUniqueness(IReadOnlyCollection<CaddyRouteSource> routes)
    {
        var duplicate = routes
            .GroupBy(
                source => (source.Route.Host, source.Route.Configuration.PathPrefix),
                StringTupleComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null)
        {
            throw new InvalidOperationException(
                $"Multiple enabled routes target {duplicate.Key.Host}{duplicate.Key.PathPrefix}.");
        }
    }

    private static string CaddyQuote(string value)
    {
        return $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal)}\"";
    }

    private static string NormalizePortalUpstream(string value)
    {
        var candidate = value.Trim();
        if (candidate.Length == 0 || candidate.Contains('\r') || candidate.Contains('\n') || candidate.Contains('{') || candidate.Contains('}'))
        {
            throw new ArgumentException("The portal upstream is invalid.", nameof(value));
        }

        return candidate;
    }

    private sealed record CertificateState(
        bool RequiresDnsChallenge,
        bool Ready,
        string ProviderType,
        string CustomerNumber,
        string ApiKey,
        string ApiPassword,
        string Endpoint,
        string Error)
    {
        public static CertificateState Individual { get; } =
            new(false, true, string.Empty, string.Empty, string.Empty, string.Empty, string.Empty, string.Empty);

        public static CertificateState Blocked(string error, string providerType = "") =>
            new(true, false, providerType, string.Empty, string.Empty, string.Empty, string.Empty, error);
    }

    private sealed class StringTupleComparer : IEqualityComparer<(string Host, string PathPrefix)>
    {
        public static StringTupleComparer Ordinal { get; } = new();

        public bool Equals((string Host, string PathPrefix) x, (string Host, string PathPrefix) y)
        {
            return string.Equals(x.Host, y.Host, StringComparison.Ordinal) &&
                   string.Equals(x.PathPrefix, y.PathPrefix, StringComparison.Ordinal);
        }

        public int GetHashCode((string Host, string PathPrefix) obj)
        {
            return HashCode.Combine(
                StringComparer.Ordinal.GetHashCode(obj.Host),
                StringComparer.Ordinal.GetHashCode(obj.PathPrefix));
        }
    }
}
