using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaddyUi.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CaddyUiDbContext))]
[Migration("20260728220200_PhaseTwoSecurityPersistence")]
public sealed class PhaseTwoSecurityPersistence : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE caddy_ui.ip_intelligence_cache (
                address inet PRIMARY KEY,
                scope character varying(24) NOT NULL,
                available boolean NOT NULL,
                asn text NOT NULL DEFAULT '',
                prefix cidr NULL,
                holder text NOT NULL DEFAULT '',
                registry text NOT NULL DEFAULT '',
                source text NOT NULL,
                payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                error text NOT NULL DEFAULT '',
                refreshed_at timestamp with time zone NOT NULL,
                expires_at timestamp with time zone NOT NULL
            );
            CREATE INDEX ix_ip_intelligence_cache_expires_at ON caddy_ui.ip_intelligence_cache (expires_at);

            CREATE TABLE caddy_ui.client_assessments (
                id uuid PRIMARY KEY,
                anonymous_client_id uuid NULL REFERENCES caddy_ui.anonymous_clients(id) ON DELETE CASCADE,
                remote_address inet NULL,
                classification text NOT NULL,
                automation_score integer NOT NULL,
                risk character varying(16) NOT NULL,
                engine_version text NOT NULL,
                sample_started_at timestamp with time zone NULL,
                sample_ended_at timestamp with time zone NULL,
                created_at timestamp with time zone NOT NULL,
                CONSTRAINT ck_client_assessments_score CHECK (automation_score BETWEEN 0 AND 100)
            );
            CREATE INDEX ix_client_assessments_client_created
                ON caddy_ui.client_assessments (anonymous_client_id, created_at DESC);

            CREATE TABLE caddy_ui.client_assessment_reasons (
                assessment_id uuid NOT NULL REFERENCES caddy_ui.client_assessments(id) ON DELETE CASCADE,
                sequence integer NOT NULL,
                code text NOT NULL,
                message text NOT NULL,
                weight integer NOT NULL,
                evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                PRIMARY KEY (assessment_id, sequence)
            );

            CREATE TABLE caddy_ui.security_events (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                occurred_at timestamp with time zone NOT NULL,
                kind text NOT NULL,
                reason text NOT NULL,
                remote_address inet NULL,
                anonymous_client_id uuid NULL REFERENCES caddy_ui.anonymous_clients(id) ON DELETE SET NULL,
                host text NOT NULL DEFAULT '',
                path text NOT NULL DEFAULT '',
                details_json jsonb NOT NULL DEFAULT '{}'::jsonb
            );
            CREATE INDEX ix_security_events_occurred_at ON caddy_ui.security_events (occurred_at DESC);
            CREATE INDEX ix_security_events_remote_address ON caddy_ui.security_events (remote_address, occurred_at DESC);

            CREATE TABLE caddy_ui.ip_block_rules (
                id uuid PRIMARY KEY,
                address_or_network cidr NOT NULL,
                reason text NOT NULL,
                source character varying(24) NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                created_at timestamp with time zone NOT NULL,
                expires_at timestamp with time zone NULL,
                released_at timestamp with time zone NULL,
                created_by_user_id uuid NULL REFERENCES caddy_ui.users(id) ON DELETE SET NULL
            );
            CREATE INDEX ix_ip_block_rules_active ON caddy_ui.ip_block_rules (expires_at)
                WHERE enabled = true AND released_at IS NULL;

            CREATE TABLE caddy_ui.ip_block_history (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rule_id uuid NULL REFERENCES caddy_ui.ip_block_rules(id) ON DELETE SET NULL,
                occurred_at timestamp with time zone NOT NULL,
                action character varying(24) NOT NULL,
                actor_user_id uuid NULL REFERENCES caddy_ui.users(id) ON DELETE SET NULL,
                reason text NOT NULL,
                snapshot_json jsonb NOT NULL
            );
            CREATE INDEX ix_ip_block_history_occurred_at ON caddy_ui.ip_block_history (occurred_at DESC);

            CREATE TABLE caddy_ui.classification_rules (
                id uuid PRIMARY KEY,
                name text NOT NULL,
                priority integer NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                actor_type character varying(16) NULL,
                request_type character varying(24) NULL,
                match_json jsonb NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX ix_classification_rules_priority ON caddy_ui.classification_rules (priority);

            CREATE TABLE caddy_ui.bot_signature_rules (
                id uuid PRIMARY KEY,
                name text NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                signature_type character varying(24) NOT NULL,
                pattern text NOT NULL,
                score integer NOT NULL,
                risk character varying(16) NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );

            CREATE TABLE caddy_ui.scheduled_jobs (
                id uuid PRIMARY KEY,
                name text NOT NULL,
                job_type text NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                schedule text NOT NULL,
                config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                last_run_at timestamp with time zone NULL,
                next_run_at timestamp with time zone NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX ix_scheduled_jobs_name ON caddy_ui.scheduled_jobs (name);

            CREATE TABLE caddy_ui.job_runs (
                id uuid PRIMARY KEY,
                job_id uuid NULL REFERENCES caddy_ui.scheduled_jobs(id) ON DELETE SET NULL,
                job_type text NOT NULL,
                state character varying(24) NOT NULL,
                started_at timestamp with time zone NOT NULL,
                completed_at timestamp with time zone NULL,
                attempt integer NOT NULL DEFAULT 1,
                result_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                error text NOT NULL DEFAULT ''
            );
            CREATE INDEX ix_job_runs_started_at ON caddy_ui.job_runs (started_at DESC);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS caddy_ui.job_runs;
            DROP TABLE IF EXISTS caddy_ui.scheduled_jobs;
            DROP TABLE IF EXISTS caddy_ui.bot_signature_rules;
            DROP TABLE IF EXISTS caddy_ui.classification_rules;
            DROP TABLE IF EXISTS caddy_ui.ip_block_history;
            DROP TABLE IF EXISTS caddy_ui.ip_block_rules;
            DROP TABLE IF EXISTS caddy_ui.security_events;
            DROP TABLE IF EXISTS caddy_ui.client_assessment_reasons;
            DROP TABLE IF EXISTS caddy_ui.client_assessments;
            DROP TABLE IF EXISTS caddy_ui.ip_intelligence_cache;
            """);
    }
}
