using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaddyUi.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CaddyUiDbContext))]
[Migration("20260728220000_PhaseTwoCorePersistence")]
public sealed class PhaseTwoCorePersistence : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "data_protection_keys",
            schema: "caddy_ui",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation(
                        "Npgsql:ValueGenerationStrategy",
                        Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                friendly_name = table.Column<string>(type: "text", nullable: true),
                xml = table.Column<string>(type: "text", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_data_protection_keys", value => value.id);
            });

        migrationBuilder.Sql(
            """
            CREATE TABLE caddy_ui.application_settings (
                key text PRIMARY KEY,
                value_json jsonb NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );

            CREATE TABLE caddy_ui.users (
                id uuid PRIMARY KEY,
                username text NOT NULL,
                display_name text NOT NULL,
                password_hash text NOT NULL,
                role character varying(16) NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                totp_secret_encrypted bytea NULL,
                totp_enabled boolean NOT NULL DEFAULT false,
                theme character varying(16) NOT NULL DEFAULT 'system',
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                last_login_at timestamp with time zone NULL,
                CONSTRAINT ck_users_role CHECK (role IN ('admin', 'editor', 'viewer')),
                CONSTRAINT ck_users_theme CHECK (theme IN ('system', 'light', 'dark'))
            );
            CREATE UNIQUE INDEX ix_users_username_normalized ON caddy_ui.users (lower(username));

            CREATE TABLE caddy_ui.user_recovery_codes (
                user_id uuid NOT NULL REFERENCES caddy_ui.users(id) ON DELETE CASCADE,
                code_hash text NOT NULL,
                created_at timestamp with time zone NOT NULL,
                used_at timestamp with time zone NULL,
                PRIMARY KEY (user_id, code_hash)
            );

            CREATE TABLE caddy_ui.admin_sessions (
                token_hash text PRIMARY KEY,
                user_id uuid NOT NULL REFERENCES caddy_ui.users(id) ON DELETE CASCADE,
                csrf_token_hash text NOT NULL,
                created_at timestamp with time zone NOT NULL,
                expires_at timestamp with time zone NOT NULL,
                remote_address inet NULL,
                user_agent text NOT NULL DEFAULT '',
                last_seen_at timestamp with time zone NOT NULL
            );
            CREATE INDEX ix_admin_sessions_expires_at ON caddy_ui.admin_sessions (expires_at);

            CREATE TABLE caddy_ui.login_attempts (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                occurred_at timestamp with time zone NOT NULL,
                scope character varying(24) NOT NULL,
                identity text NOT NULL DEFAULT '',
                remote_address inet NULL,
                succeeded boolean NOT NULL,
                reason text NOT NULL DEFAULT ''
            );
            CREATE INDEX ix_login_attempts_scope_identity ON caddy_ui.login_attempts (scope, identity, occurred_at DESC);
            CREATE INDEX ix_login_attempts_remote_address ON caddy_ui.login_attempts (remote_address, occurred_at DESC);

            CREATE TABLE caddy_ui.login_blocks (
                id uuid PRIMARY KEY,
                scope character varying(24) NOT NULL,
                identity text NOT NULL DEFAULT '',
                remote_address inet NULL,
                reason text NOT NULL,
                created_at timestamp with time zone NOT NULL,
                expires_at timestamp with time zone NOT NULL,
                released_at timestamp with time zone NULL
            );
            CREATE INDEX ix_login_blocks_active ON caddy_ui.login_blocks (expires_at) WHERE released_at IS NULL;

            CREATE TABLE caddy_ui.access_groups (
                id uuid PRIMARY KEY,
                name text NOT NULL,
                config_json jsonb NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX ix_access_groups_name_normalized ON caddy_ui.access_groups (lower(name));

            CREATE TABLE caddy_ui.access_credentials (
                id uuid PRIMARY KEY,
                group_id uuid NOT NULL REFERENCES caddy_ui.access_groups(id) ON DELETE CASCADE,
                username text NOT NULL,
                password_hash text NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX ix_access_credentials_group_username
                ON caddy_ui.access_credentials (group_id, lower(username));

            CREATE TABLE caddy_ui.portal_sessions (
                token_hash text PRIMARY KEY,
                credential_id uuid NOT NULL REFERENCES caddy_ui.access_credentials(id) ON DELETE CASCADE,
                group_id uuid NOT NULL REFERENCES caddy_ui.access_groups(id) ON DELETE CASCADE,
                created_at timestamp with time zone NOT NULL,
                expires_at timestamp with time zone NOT NULL,
                user_agent text NOT NULL DEFAULT '',
                remote_address inet NULL
            );
            CREATE INDEX ix_portal_sessions_expires_at ON caddy_ui.portal_sessions (expires_at);

            CREATE TABLE caddy_ui.dns_providers (
                id uuid PRIMARY KEY,
                provider_type text NOT NULL,
                label text NOT NULL,
                config_json jsonb NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );

            CREATE TABLE caddy_ui.managed_routes (
                id uuid PRIMARY KEY,
                name text NOT NULL,
                host text NOT NULL,
                kind character varying(24) NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                config_json jsonb NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX ix_managed_routes_name_normalized ON caddy_ui.managed_routes (lower(name));
            CREATE INDEX ix_managed_routes_host ON caddy_ui.managed_routes (lower(host));

            CREATE TABLE caddy_ui.route_revisions (
                id uuid PRIMARY KEY,
                created_at timestamp with time zone NOT NULL,
                actor_user_id uuid NULL REFERENCES caddy_ui.users(id) ON DELETE SET NULL,
                reason text NOT NULL,
                manifest_json jsonb NOT NULL,
                content_json jsonb NOT NULL,
                digest text NOT NULL,
                applied boolean NOT NULL DEFAULT false
            );
            CREATE INDEX ix_route_revisions_created_at ON caddy_ui.route_revisions (created_at DESC);
            CREATE INDEX ix_route_revisions_digest ON caddy_ui.route_revisions (digest);

            CREATE TABLE caddy_ui.apply_operations (
                id uuid PRIMARY KEY,
                route_revision_id uuid NULL REFERENCES caddy_ui.route_revisions(id) ON DELETE SET NULL,
                actor_user_id uuid NULL REFERENCES caddy_ui.users(id) ON DELETE SET NULL,
                correlation_id text NOT NULL,
                state character varying(24) NOT NULL,
                started_at timestamp with time zone NOT NULL,
                completed_at timestamp with time zone NULL,
                error text NOT NULL DEFAULT '',
                previous_snapshot_id uuid NULL
            );
            CREATE UNIQUE INDEX ix_apply_operations_correlation_id ON caddy_ui.apply_operations (correlation_id);
            CREATE INDEX ix_apply_operations_started_at ON caddy_ui.apply_operations (started_at DESC);

            CREATE TABLE caddy_ui.apply_operation_steps (
                operation_id uuid NOT NULL REFERENCES caddy_ui.apply_operations(id) ON DELETE CASCADE,
                sequence integer NOT NULL,
                name text NOT NULL,
                state character varying(24) NOT NULL,
                started_at timestamp with time zone NULL,
                completed_at timestamp with time zone NULL,
                details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                error text NOT NULL DEFAULT '',
                PRIMARY KEY (operation_id, sequence)
            );

            CREATE TABLE caddy_ui.caddy_snapshots (
                id uuid PRIMARY KEY,
                created_at timestamp with time zone NOT NULL,
                digest text NOT NULL,
                manifest_json jsonb NOT NULL,
                content_json jsonb NOT NULL,
                reason text NOT NULL
            );
            CREATE UNIQUE INDEX ix_caddy_snapshots_digest ON caddy_ui.caddy_snapshots (digest);

            ALTER TABLE caddy_ui.apply_operations
                ADD CONSTRAINT fk_apply_operations_previous_snapshot
                FOREIGN KEY (previous_snapshot_id)
                REFERENCES caddy_ui.caddy_snapshots(id)
                ON DELETE SET NULL;

            CREATE TABLE caddy_ui.audit_events (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                occurred_at timestamp with time zone NOT NULL,
                actor_user_id uuid NULL REFERENCES caddy_ui.users(id) ON DELETE SET NULL,
                actor_username text NOT NULL,
                remote_address inet NULL,
                action text NOT NULL,
                object_type text NOT NULL,
                object_id text NOT NULL,
                before_json jsonb NOT NULL,
                after_json jsonb NOT NULL,
                result text NOT NULL,
                revision_id uuid NULL,
                correlation_id text NOT NULL,
                legacy_source_digest text NULL,
                legacy_source_id bigint NULL
            );
            CREATE INDEX ix_audit_events_occurred_at ON caddy_ui.audit_events (occurred_at DESC);
            CREATE UNIQUE INDEX ix_audit_events_legacy
                ON caddy_ui.audit_events (legacy_source_digest, legacy_source_id)
                WHERE legacy_source_digest IS NOT NULL AND legacy_source_id IS NOT NULL;

            CREATE TABLE caddy_ui.notifications (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at timestamp with time zone NOT NULL,
                severity character varying(16) NOT NULL,
                event_type text NOT NULL,
                title text NOT NULL,
                message text NOT NULL,
                object_type text NOT NULL DEFAULT '',
                object_id text NOT NULL DEFAULT '',
                acknowledged_at timestamp with time zone NULL,
                legacy_source_digest text NULL,
                legacy_source_id bigint NULL
            );
            CREATE INDEX ix_notifications_created_at ON caddy_ui.notifications (created_at DESC);
            CREATE UNIQUE INDEX ix_notifications_legacy
                ON caddy_ui.notifications (legacy_source_digest, legacy_source_id)
                WHERE legacy_source_digest IS NOT NULL AND legacy_source_id IS NOT NULL;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS caddy_ui.notifications;
            DROP TABLE IF EXISTS caddy_ui.audit_events;
            DROP TABLE IF EXISTS caddy_ui.apply_operation_steps;
            DROP TABLE IF EXISTS caddy_ui.apply_operations;
            DROP TABLE IF EXISTS caddy_ui.caddy_snapshots;
            DROP TABLE IF EXISTS caddy_ui.route_revisions;
            DROP TABLE IF EXISTS caddy_ui.managed_routes;
            DROP TABLE IF EXISTS caddy_ui.dns_providers;
            DROP TABLE IF EXISTS caddy_ui.portal_sessions;
            DROP TABLE IF EXISTS caddy_ui.access_credentials;
            DROP TABLE IF EXISTS caddy_ui.access_groups;
            DROP TABLE IF EXISTS caddy_ui.login_blocks;
            DROP TABLE IF EXISTS caddy_ui.login_attempts;
            DROP TABLE IF EXISTS caddy_ui.admin_sessions;
            DROP TABLE IF EXISTS caddy_ui.user_recovery_codes;
            DROP TABLE IF EXISTS caddy_ui.users;
            DROP TABLE IF EXISTS caddy_ui.application_settings;
            """);

        migrationBuilder.DropTable(
            name: "data_protection_keys",
            schema: "caddy_ui");
    }
}
